<?php $this->headTitle($title); ?>
<div class="row">
    <div class="large-12 columns">

        <!-- Desktop Slider -->

        <div class="hide-for-small">
            <div id="featured">
                <img src="<?php echo $this->basePath('img/slides/EEC-exams.jpg');?>" />
            </div>
        </div>

        <!-- End Desktop Slider -->


        <!-- Mobile Header -->


        <div class="row">
            <div class="small-12 show-for-small"><br>
                <img src="<?php echo $this->basePath('img/slides/EEC-exams.jpg');?>" />
            </div>
        </div>


        <!-- End Mobile Header -->
    <hr />
    </div>
</div><br>

<div class="row">
    <div class="large-12 columns">
        <div class="row">

            <!-- Thumbnails -->

            <div class="large-3 small-6 columns">
                <img src="<?php echo $this->basePath('img/slides/PET-exams-small.jpg');?>" />
                <h6 class="panel">Examinarea Cambridge in limba engleza PET este o calificare de nivel pre-intermediar, care testeaza abilitatile lingvistice caracteristice vietii sociale si profesionale, intr-un mediu de limba engleza.<br/><br/>
                    <button class="button tiny">
                        afla mai multe
                    </button>
                </h6>
            </div>

            <div class="large-3 small-6 columns">
                <img src="<?php echo $this->basePath('img/slides/CAE-exams-small.jpg');?>" />
                <h6 class="panel">Considerat a fi cel mai popular examen Cambridge din Romania, CAE (Certificate in Advanced English) este recunoscut si acceptat de universitati de stat si private, ca substitut al testului de admitere sau al altor examene similare.<br/><br/>
                    <button class="button tiny">
                        afla mai multe
                    </button>
                </h6>
            </div>

            <div class="large-3 small-6 columns">
                <img src="<?php echo $this->basePath('img/slides/BEC-exams-small.jpg');?>" />
                <h6 class="panel">Colaborand cu orice instituție publică sau privată din Romania, European Examinations Centre organizeaza examinari Cambridge de engleza pentru afacer<br/><br/>
                    <button class="button tiny">
                        afla mai multe
                    </button>
                </h6>
            </div>

            <div class="large-3 small-6 columns">
                <img src="<?php echo $this->basePath('img/slides/KET-exams-small.jpg');?>" />
                <h6 class="panel">Examinarea Cambridge in limba engleza KET testează capacitatea candidatului de a se exprima in situatii cotidiene uzuale si de a intelege informatii scurte si texte simple.<br/><br/>
                    <button class="button tiny">
                        afla mai multe
                    </button>
                </h6>
            </div>

            <!-- End Thumbnails -->

        </div>
    </div>

</div>



<div class="row">
    <div class="large-12 columns">
        <div class="row">

            <!-- Content -->

            <div class="large-12 columns">

                <p>Cambridge English ofera o varietate de examene de limba engleza dedicate atat elevilor incepand cu varsta de 7 ani cat si adultilor dornici de obtinerea unor certificate recunoscute international.  Prin obtinerea unei diplome Cambridge candidatul isi va creste sansele de a continua educatia in Romania sau in strainatate in cele mai prestigioase institutii de invatamant sau de a obtine un post intr-o companie din tara sau din afara Romaniei.</p>
                <p>Mai mult, incepand din anul 2010 probele de competenta ligvistica din cadrul bacalaureatului pot fi echivalate cu certificarile de limbi straine obtinute in urma sustinerii examenelor internationale.</p>
                <p>Examenele sustinute prin centrul nostru sunt echivalate pe Scala Comuna Europeana de Referinta pentru Limbi Straine publica de Consiliul Europei</p>
                <p>EEC Romania ofera atat varianta de examen paper based cat si computer based, folosind propria reteaua de laptopuri, astfel incat confortul candidatilor sa fie asigurat. Daca sustineti un examen Cambridge pe calculator veti obtine acelasi certificat recunoscut international precum cel obtinut in urma sustinerii examenului in varianta standard, pe suport de hartie.</p>
                <p>Examenele sustinute pe calculator sunt ideale atunci cand un candidat se simte mai confortabil folosind tastatura si mouse-ul decat hartia si creionul, insa exista si alte befecii:</p>
                <ul>
                    <li>Rezultatele pot fi vizualizate online in doar trei saptamani de la sustinerea testului.</li>
                    <li>Examenul pe calculator este intuitiv, foloseste un cronometru online iar  functia ajutor va permite candidatului sa obtina cele mai bune rezultate.</li>
                    <li>Candidatul isi poate schimba raspunsurile pe loc in timpul desfasurarii examenului.</li>
                    <li>Se folosesc casti individuale pentru proba de ascultare (Listening) ce permite ajustarea volumului conform nevoilor fiecarui candidat.</li>
                </ul>
                <p class="pagination-centered"><iframe width="360" height="203" src="//www.youtube.com/embed/QEwwX9EGr84" frameborder="0" allowfullscreen></iframe></p>
            </div>

            <!-- End Content -->

        </div>
    </div>
</div>