<?php $this->headTitle($title); ?>

<!-- First Band (Slider) -->

<div class="row">
    <div class="large-12 columns">
        <ul data-orbit>
            <li>
                <img src="<?php echo $this->basePath('img/slides/cambridge-by-EEC.jpg');?>" alt="Cambridge by eeCentre.ro"/>
            </li>
            <li>
                <img src="<?php echo $this->basePath('img/slides/inscriere-EEC.jpg');?>" alt="inscriere eeCentre.ro"/>
            </li>
            <li>
                <img src="<?php echo $this->basePath('img/slides/galerie-EEC.jpg');?>" alt="galerie eeCentre.ro"/>
            </li>
            <li>
                <img src="<?php echo $this->basePath('img/slides/promo-EEC.jpg');?>" alt="promo eeCentre.ro"/>
            </li>
            <li>
                <img src="<?php echo $this->basePath('img/slides/contact-EEC.jpg');?>" alt="contact eeCentre.ro"/>
            </li>
            <li>
                <img src="http://placehold.it/1000x400&text=[ img 4 ]" />
                <div class="orbit-caption">Test caption for picture 4</div>
            </li>
        </ul>
        <!-- <div id="slider">

        </div> -->

        <hr />
    </div>
</div>

<!-- Three-up Content Blocks -->

<div class="row">
    <div class="large-4 columns">
        <img src="<?php echo $this->basePath('img/slides/PET-exams-small.jpg');?>" alt="PET exams eeCentre.ro"/>
        <h4>This is a content section.</h4>
        <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>

    <div class="large-4 columns">
        <img src="<?php echo $this->basePath('img/slides/CAE-exams-small.jpg');?>" alt="CAE exams eeCentre.ro"/>
        <h4>This is a content section.</h4>
        <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>

    <div class="large-4 columns">
        <img src="<?php echo $this->basePath('img/slides/BEC-exams-small.jpg');?>" alt="BEC exams eeCentre.ro"/>
        <h4>This is a content section.</h4>
        <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
    </div>

</div>

<!-- Call to Action Panel -->
<div class="row">
    <div class="large-12 columns">

        <div class="panel">
            <h4>Get in touch!</h4>

            <div class="row">
                <div class="large-9 columns">
                    <p>We'd love to hear from you, you attractive person you.</p>
                </div>
                <div class="large-3 columns">
                    <a href="<?php echo $this->url('contact', array('action' => 'index'));?>" class="radius button right">Contact Us</a>
                </div>
            </div>
        </div>

    </div>
</div>